### ISSUE TITLE
Final_HEL_Summary layer missing 'MUHELCL' field -- Error 000218

### ISSUE THREAD

**Issue by danielshults19** [USDA-NRCS/HEL-Tools#31] opened 2023-12-26 20:08 UTC
I tried running the tool with the consolidate box checked and unchecked with the same error. 

Running Pro 3.1.3

![image](https://github.com/USDA-NRCS/HEL-Tools/assets/154926311/8ea24b00-5d6e-4732-9b54-21e9dca0cbdb)

**Comment by dylan-harwell-usda** [comment] 2023-12-26 20:25
@danielshults19 Thanks for the report.

Import Office Addresses is setup, it's in the Utilities toolset. What you did is correct by editing the CSVs in the Templates directory, then the idea is you run the Import Office Address tool which adds them to the Support GDB. 

As for this error, can you include a screenshot of the schema of your Final_HEL_Summary layer? The statistics tool uses several fields as 'Case' fields from this layer. First guess here, somehow the schema is different than the tool is expecting.

**Comment by danielshults19** [comment] 2023-12-26 20:28
Thank you Dylan, sorry. I overlooked the tool, it worked. 

![image](https://github.com/USDA-NRCS/HEL-Tools/assets/154926311/29e6fc1b-4af1-4de1-9677-ceba5b01c4ad)
![image](https://github.com/USDA-NRCS/HEL-Tools/assets/154926311/b82d99b6-1cac-4534-b7d3-c4d3a0d0cc36)

**Comment by dylan-harwell-usda** [comment] 2023-12-26 20:31
Well that is interesting, I see the problem. The layer is missing the 'MUHELCL' field, which is used by the Statistics tool:
`case_field = ['clu_number', 'MUSYM', 'MUHELCL', 'Final_HEL_Value'])`
So that makes me think your input soils data is missing that field.

**Comment by danielshults19** [comment] 2023-12-26 20:36
Well, I was sure that I changed the casing of them to be identical to the document but I guess I didn't hit save. I'll try it again with the exact casing. 

![image](https://github.com/USDA-NRCS/HEL-Tools/assets/154926311/39123850-a0e7-4997-a5fd-c5248073daab)

**Comment by dylan-harwell-usda** [comment] 2023-12-26 20:43
I don't think the field names are case sensitive. When I say case here, that's referring to a parameter of the Statistics tool. That's very interesting that your soils layer has that MUHELCL field, but your Final_HEL_Summary layer does not. No idea how that could happen. That field is used a lot in the Determination algorithm, which then creates that summary layer. I may have to defer this one to Chris Morse as I am not familiar with the expected schema of the soils data, or if the original tool was designed to handle different input schemas. But yea.. if your Final_HEL_Summary layer is missing that field, that explains the error you got from the Form, Letter, Report tool :/

**Comment by danielshults19** [comment] 2023-12-26 20:49
Ahhh, okay. I didn't think it should matter but what do I know haha. I ran it again for the heck of it, and got the same error. Just reach out whenever.

**Comment by dylan-harwell-usda** [comment] 2023-12-26 20:55
Curious, your Determination script ran successfully??

**Comment by danielshults19** [comment] 2023-12-26 20:57
Yes

**Comment by danielshults19** [comment] 2023-12-26 20:57
![image](https://github.com/USDA-NRCS/HEL-Tools/assets/154926311/5cbea27e-5b1f-4e87-9e4c-60e74be4025c)

**Comment by dylan-harwell-usda** [comment] 2023-12-26 20:59
Does your Initial_HEL_Summary layer have the 'MUHELCL' field?

**Comment by danielshults19** [comment] 2023-12-26 21:00
Yes
![image](https://github.com/USDA-NRCS/HEL-Tools/assets/154926311/c1e68a9d-1edd-45e5-87f3-52e8a5207c97)

**Comment by dylan-harwell-usda** [comment] 2023-12-26 21:03
Very weird. Haven't seen this happen before, but unfortunately I can only test these tools for Tracts in Indiana with a sample soils dataset that Chris Morse gave me. What State/County/Tract are you running this for?
Since we haven't had any other reports of this, it makes me feel like it has to be something to do with a difference in input data, but that's just my first theory at this point.

**Comment by danielshults19** [comment] 2023-12-26 21:08
Arkansas, White County, Tract 9806

Just a test location that I chose, I can choose another and test it?

**Comment by dylan-harwell-usda** [comment] 2023-12-26 21:24
One thing that strikes me as odd here, is that your input soils layer does not have the 'MUSYM' field, it has 'AREASYMBOL_MUSYM_1' and 'musym2' -- but then somehow your Final_HEL_Summary layer has 'MUSYM'. That doesn't make sense because I don't see anything in the code explicitly creating that field.
If you take a look inside Sample/sample.gdb, the soils layer Chris gave me is in091_national_hel and the schema is quite different. Although the important fields all look to be present in your soils layer, minus 'MUSYM'.

**Comment by danielshults19** [comment] 2023-12-26 21:37
Well the dataset does have the 'MUSYM' field, you just couldn't see it in that screenshot that I sent you. Would you like for me to send you the data to review?

**Comment by dylan-harwell-usda** [comment] 2024-01-02 23:01
Cleaned up some of the conversation on this one to reply to the last comments regarding case sensitivity and if Determination ran successfully.

I believe I found the issue - the MUHELCL field is case-sensitive for certain situations. None of the geoprocessing steps fail in the Determination script, but the tool is expecting that field, along with all of the other's used in the input soils data to be upper-case, and thus when it creates the Final_HEL_Summary layer, it's missing any that are lower-case.

Another user that ran into this was missing all 5 of the expected fields from their Final_HEL_Summar layer: `'MUHELCL', 'MUSYM', 'MUNAME', 'MUWATHEL', 'MUWNDHEL'`.

In your case here Daniel, it looks like your Final_HEL_Summary layer contains 3 of those - the 3 that are upper-case in your input soils layer.

Chris Morse and I are discussing whether to handle this in code or whether to force users to have upper-case fields to work with the current tool code.

**Comment by danielshults19** [comment] 2024-01-03 17:29
The casing fixed the issue, everything seems to working as it should now. Thank you for all the help! "MUNAME" is also sensitive to the casing issue, therefore they all may need upper casing to populate in the Final Summary.

**Comment by dylan-harwell-usda** [comment] 2024-01-03 22:37
At this time, no code fix for this issue. The tool will require user's input data to have upper-case fields matching what the tool expects.

**Comment by dylan-harwell-usda** [comment] 2024-01-12 20:17
Chris Morse discovered that ESRI Hosted services automatically make fields lower-case. After this discovery, we have decided to update the script to handle field names dynamically. Reopening issue.

**Closed** 2024-01-25 21:42 UTC
Labels: in-progress
