### ISSUE TITLE
Running a determination right after one does not display the newest Field Determination on the map

### ISSUE THREAD

**Issue by ksduncan** [USDA-NRCS/HEL-Tools#30] opened 2023-12-20 20:42 UTC
Testers tried running one determination after another. The process went smoothly till step B .01. HEL Determination. The process ran correctly, but the layers did not update on the map. It still displayed the first determination and it's the summary layers they created. All the other layers properly updated and displayed in the previous steps. 

The layers did correctly get created in the geodatabase. They would prefer to not have to open up a new ArcPro project each time to run a new determination.

**Comment by dylan-harwell-usda** [comment] 2023-12-20 21:04
@ksduncan - Just so I am clear about what you are describing, were they trying to run a Determination for _different_ county/tract/farm combinations in the same map? Or were they just running the Determination tool over and over for the same county/tract/farm?

**Comment by dylan-harwell-usda** [comment] 2023-12-20 22:15
@ksduncan - If they were attempting to run multiple determinations for different county/tract combinations, the workflow was not designed for that. Similar to Wetlands, the process creates a unique folder, geodatabase, tables, layers, etc for a unique county and tract combination. The idea is that you save your APRX file specific for each county/tract in the folder that gets created.
![image](https://github.com/USDA-NRCS/HEL-Tools/assets/120053864/6238af48-d900-4e00-ba02-16a212791959)

So if you run through the process for a different county/tract than the first, a new folder is created and those layers go into that corresponding geodatabase, and would explain why the map is not updating with those new determination layers.

Please correct me if I am misunderstanding the issue you described. But opening a new Pro project and running through the toolbox starting at the Create Project tool is all done by design. Closing issue.

**Closed by dylan-harwell-usda** 2023-12-20 22:15 UTC
